changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/test.{js,ts,jsx,tsx}"
  - "**/*.spec.{js,ts,jsx,tsx}"

compressionLevel: 0

defaultSemverRangePrefix: ""

enableScripts: false

npmRegistryServer: 'https://registry.npmjs.org'

# 3 days, keep inline with .ncurc.cjs and renovate.json5
npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - '@belgattitude/*'
  - '@flowblade/*'
  - '@httpx/*'
  - 'esbuild'
  - '@esbuild/*'
  - 'hono'
  - 'vite'
  - '@vitejs/*'
  - 'vitest'
  - '@vitest/*'
  - '@cloudflare/vitest-pool-workers'
  - 'miniflare'
  - 'wrangler'

npmPublishProvenance: true

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
