changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/test.{js,ts,jsx,tsx}"
  - "**/*.spec.{js,ts,jsx,tsx}"

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

compressionLevel: mixed

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.39.cjs
