changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/test.{js,ts,jsx,tsx}"
  - "**/*.spec.{js,ts,jsx,tsx}"

compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@belgattitude/*"
  - "@flowblade/*"
  - "@httpx/*"
  - esbuild
  - "@esbuild/*"
  - hono
  - vite
  - "@vitejs/*"
  - vitest
  - "@vitest/*"
  - "@cloudflare/vitest-pool-workers"
  - miniflare
  - wrangler
  - tsdown
  - "happy-dom"
  - pino
  - obug
  - rolldown-plugin-dts
  - rolldown
  - unrun
  - "@rolldown/*"
  - tsdown
  - import-without-cache
  - "@oxc-project/*"
  - "@napi-rs/*"
  - birpc
  - tsup
  - prettier
  - next
  - "@next/*"
  - "@typescript-eslint/*"
  - 'es-check'
  - 'baseline-browser-mapping'


npmPublishProvenance: true

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

