import { HttpBadRequest } from '@httpx/exception';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const error = new HttpBadRequest('hello');

  return (
    <div className={styles.container}>
      <Head>
        <title>Example nextjs app (esm)</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/examples/nextjs-app/public/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        It will display
        <div>
          HttpBadRequest - <span>{error.message}</span>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          rel="noopener noreferrer"
          target="_blank"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image alt="Vercel Logo" height={16} src="/vercel.svg" width={72} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
