name: CI-examples

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7

      - name: ⚙️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: 🏗 Build packages
        run: yarn workspaces foreach -v --worktree --from '@httpx/*' run build

      - name: 🕵️ Typecheck
        run: yarn workspaces foreach -v --worktree --from '@examples/*' run typecheck

      - name: 🕵️ Typecheck (no typescript path aliases)
        run: yarn workspaces foreach -v --worktree --from '@examples/*' run typecheck-no-paths


      - name: 🔬 Lint
        run: yarn workspaces foreach -v --worktree --from '@examples/*' run lint

      - name: 🏗 Build example apps
        run: yarn workspaces foreach -v --worktree --from '@examples/*' run build
        env:
          NEXTJS_IGNORE_ESLINT: true
          NEXTJS_IGNORE_TYPECHECK: true
          NEXT_DISABLE_SOURCEMAPS: true
          NEXT_TELEMETRY_DISABLED: true
